spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/streaming_db
    username: postgres
    password: Minh123_A
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  minio:
    url: http://localhost:9000
    access-key: melody
    secret-key: melody123
    secure: false
    bucket-name: melody-stream

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: Minh123_A

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  security:
    user:
      name: user
      password: Minh123_A

  rabbitmq:
    host: localhost
    port: 5672
    username: melody
    password: melody123
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 2
        max-concurrency: 6

# JWT
jwt:
  access-secret:  ${JWT_ACCESS_SECRET}   # min 32 chars
  refresh-secret: ${JWT_REFRESH_SECRET}  # min 32 chars
  access-ttl-ms:  900000          # 15 minutes
  refresh-ttl-ms: 604800000       # 7 days

# Async thread pool for mail
spring.task.execution:
  pool:
    core-size: 2
    max-size: 5
    queue-capacity: 100


springdoc:
  api-docs:
    enabled: true
    path: "/api-docs/json"
  swagger-ui:
    path: "/api-docs"
  show-actuator: true

app:
   jobs:
    process-music:
       exchange: jobs.exchange
       routing-key: jobs.process-music
       queue: process-music.queue
       retry:
         exchange: jobs.retry.exchange
         rk10s: jobs.process-music.retry.10s
         rk60s: jobs.process-music.retry.60s
         queue10s: process-music.retry.10s.queue
         queue60s: process-music.retry.60s.queue
         max-attempts: 5
       dlq:
         exchange: jobs.dlq.exchange
         routing-key: jobs.process-music.dlq
         queue: process-music.dlq

   base-url: ${APP_BASE_URL:http://localhost:8080}
   frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}

kind: "Application"

